# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[>>-](bright-black) $all\
$fill\
$time\
$line_break\
[>>-](bright-black) $character
"""

# Inserts a blank line between shell prompts
add_newline = true

[fill]
symbol = " "

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[line_break]
disabled = false

[time]
disabled = false
format = '[  $time ](fg:blue bold)'
time_format = "%F %R"
utc_time_offset = "9"
